/****************************************************************************************
*                                    SENTINEL PROGRAM
*****************************************************************************************
* NAME:  cc_macvars.sas
*
* PURPOSE:  AFTER a new ETL has been approved and has passed CC testing, this program is
*           called by Production requests in order to define all global macro variables
*           needed, including:
*
*           DP
*           ETL
*           PHASE (Phase A=non-MIL tables or B=all SCDM tables plus MIL)
*           SCDMVER (7.0.0 and higher)
*           ENRTABLE
*           DEMTABLE
*           DISTABLE
*           DIATABLE
*           PROCTABLE
*           ENCTABLE
*           DEATHTABLE (if availabe at the site)
*           CODTABLE (if availabe at the site)
*           LABTABLE (if availabe at the site)
*           VITTABLE (if availabe at the site)
*           IPHARMTABLE (if availabe at the site)
*           ITRANSTABLE(if availabe at the site)
*           MILTABLE (if availabe at the site, Phase B only)
*           PRETABLE (if available at the site)
*           FACTABLE
*           PVDTABLE
*           DPLOCAL
*           INFOLDER
*           MSOC
*           SASPROGRAMS
*           INDATA
*
* MAJOR STEPS:
*       1. DPs run CC testing, which contains all necessary metadata files (included by
*          SOC) that have been generated by the QA package (standard and/or MIL QA)
*          Additonal metadata files are written to the CC request DPLOCAL folder.
*       2. Production level package headers will include DP input for &SCC, which is
*          this request, including the CC request ID
*          (e.g. //sentinel/etl22/phasea/requests/soc_cca_wp001_xxxx_v01/)
*       3. Production level package header will call (%include) this module to produce
*          all global macro variables need for the query.
*       4. Execute the SOC_SETUP_MACROS.sas, located within the inputfiles
*          subdirectory of this CC request
*       5. Create the specified macro variables and librefs, listed above and
*          described in the functional specifications for this program package.
*
* KEY DEPENDENCIES/CONSTRAINTS:
*       - SAS dataset metadata files from of QA package in DP_metadata subdirectory
*       - Successful execution of this request to test parameters out and create SAS
*         datasets containing metadata files from execution of this CC request
*         (CC_TEST). Output should be written the DPLOCAL subdirectory of this CC
*         request.
*
*----------------------------------------------------------------------------------------
* CONTACT INFO:
*  Sentinel Coordinating Center
*  info@sentinel.org
*--------------------------------------------------------------------------------------*/

%global INDATA DPLOCAL MSOC INFOLDER SASPROGRAMS;

%include "&SCC./inputfiles/soc_setup_macros.sas"/nosource2;

%let SCC=%soc_clean_paths(&SCC.);

%let CCRESULT = &SCC.msoc/ &SCC./dplocal/;
%soc_lib(CCRESULT,&CCRESULT)

%let QARESULT = &SCC.inputfiles/dp_metadata/;
%soc_lib(QARESULT,&QARESULT)

proc sql noprint;
  select value into :INDATA trimmed
  from ccresult.cc_request_paths (where=(lowcase(variable)="indata"))
  ;
quit;
%soc_lib(INDATA,&INDATA)

%macro request_root;
  %local k;
  proc sql noprint;
    select "_root_"||variable
         , value
         , count(*)
    into :varlist separated by " "
       , :vallist separated by " "
       , :ct trimmed
    from ccresult.cc_request_paths (where=(lowcase(variable) ne "indata"))
    ;
  quit;

  %global &varlist.;

  %do k=1 %to &ct.;
     %let var=%scan(&varlist,&k,%str( ));
     %let val=%qscan(&vallist,&k,%str( ));
     %let %superq(var) = %soc_clean_paths(&val) ;
  %end;
%mend request_root;
%request_root

%let DPLOCAL=&_root_dplocal.&reqid./dplocal/;
%let INFOLDER=&_root_inputfiles.&reqid./inputfiles/;
%let MSOC=&_root_msoc.&reqid./msoc/;
%let SASPROGRAMS=&_root_sasprograms.&reqid./sasprograms/;

%macro macvar(name);
  %global &name;
  proc sql noprint;
    select value into :%superq(name) trimmed
    from qaresult.qa_cc_metadata (where=(lowcase(variable)=lowcase("&name.")))
    ;
  quit;
%mend macvar;
%macvar(dp)
%macvar(etl)
%macvar(phase)

/* Conditional code to force the current SCDM version (e.g. 7.0.0) if not already in the metadata file */
/* Consider removing after all DP sites update to SCDM v8.0.0 */
%macro ifnotexist;
  %let exist = 0;
   proc sql noprint;
	 select count(*) into :exist from qaresult.qa_cc_metadata (where=(lowcase(variable)="scdmver"))
     ;
   quit;
   %if &exist. %then %do;
      %macvar(scdmver);
   %end;
   %else %do;
     %global scdmver;
	 %let scdmver=7.0.0;
   %end;
%mend;
%ifnotexist;


%macro datevars(date);
  %global &date;
  proc sql noprint;
    select input(value,date9.) into :%superq(date) trimmed
    from qaresult.qa_cc_metadata (where=(lowcase(variable)=lowcase("&date.")))
    ;
  quit;

  %put *** %superq(date): %sysfunc(putn(%superq(&date), date9.));
%mend datevars;
%datevars(DP_mindate)
%datevars(DP_maxdate)

%macro scdm_table_names;
  %local k;
  /* create global list of all SCDM table macro variables */
  proc sql noprint;
    select variable into :alllist separated by " "
    from qaresult.qa_cc_metadata (where=(index(variable,"TABLE") ne 0))
    ;
  quit;
  %global &alllist;

  proc sql noprint;
    select variable
         , value
         , count(*)
    into :varlist separated by " "
       , :vallist separated by " "
       , :ct trimmed
    from qaresult.qa_cc_metadata (where=(index(variable,"TABLE") ne 0 and lowcase(value) not in (' ', 'na')))
    ;
  quit;

  %do k=1 %to &ct.;
     %let var=%scan(&varlist,&k,%str( ));
     %let val=%unquote(%qscan(&vallist,&k,%str( )));
     %let %superq(var) = &val ;
  %end;

  %if %lowcase(&phase)=a %then %let miltable=;
%mend scdm_table_names;
%scdm_table_names;